### ISSUE TITLE
ExecuteNonQuery failed for Database 'master'

### ISSUE THREAD

**Issue by jimbrew** [phola/SSRS-Docker#1]
Hello I get an issue when the docker image runs it seems to be the start script that is failing.

In the logs in docker this is what is presented -

C:\start.ps1 : Exception calling "ExecuteNonQuery" with "1" argument(s):
"ExecuteNonQuery failed for Database 'master'. "
At line:1 char:76
... yContinue'; .\start -sa_password $env:sa_password -ACCEPT_EULA $env:A ...
CategoryInfo : NotSpecified: (:) [start.ps1], MethodInvocationException
FullyQualifiedErrorId : FailedOperationException,start.ps1

**Comment by cannonfodda** [comment]
Was having the same issue on Win 10 with Docker Desktop 2.2.0.4 and it took me days to work out where things are going wrong.

Turns out that SQL is dying with an OOM exception when the configureSSRS2017.ps1 script is trying to set up the database permissions. The solution that worked for me was to stop using docker-compose and go back to command line docker and specify higher memory limits with:

docker build --memory 12GB <name>

From a bit of experimentation it looks like the container needs at least 12GB. Not sure what the default is in Windows 10 Docker Desktop.

**Comment by phola** [comment]
You can also set memory here https://github.com/phola/SSRS-Docker/blob/master/README.md#tips

**Comment by daniel-fahey** [comment]
The only way I could get it to run was to build the container first like:
`docker build -m 16GB -t ssrs .`
and then running the built container like:
`docker run -d -p 1433:1433 -p 80:80 -e sa_password=<strongpass1> -e ACCEPT_EULA=Y -e ssrs_user=<username> -e ssrs_password=<strongpass2> --memory 16g ssrs`
